# Production Environment Configuration
# This file contains production-specific settings with security and performance optimizations

[database]
# Production database settings with connection pooling optimization
max_connections = 50
min_connections = 10
connection_timeout_seconds = 30
idle_timeout_seconds = 300
max_lifetime_seconds = 1800
enable_logging = false
slow_query_threshold_ms = 1000
replica_urls = []
enable_read_replicas = true

[api]
host = "0.0.0.0"
port = 8080
cors_origins = []  # Configure with actual production domains
request_timeout_seconds = 30
max_request_size_mb = 16
rate_limit_requests_per_minute = 1000
enable_compression = true
enable_metrics = true

# TLS configuration for production (uncomment and configure)
# [api.tls]
# cert_file = "/etc/ssl/certs/defi-risk-monitor.crt"
# key_file = "/etc/ssl/private/defi-risk-monitor.key"
# ca_file = "/etc/ssl/certs/ca-bundle.crt"

[blockchain]
# Production RPC endpoints - configure with your actual endpoints
ethereum_rpc_url = "https://mainnet.infura.io/v3/YOUR_PROJECT_ID"
ethereum_ws_url = "wss://mainnet.infura.io/ws/v3/YOUR_PROJECT_ID"
polygon_rpc_url = "https://polygon-mainnet.infura.io/v3/YOUR_PROJECT_ID"
arbitrum_rpc_url = "https://arbitrum-mainnet.infura.io/v3/YOUR_PROJECT_ID"
optimism_rpc_url = "https://optimism-mainnet.infura.io/v3/YOUR_PROJECT_ID"
bsc_rpc_url = "https://bsc-dataseed.binance.org"
avalanche_rpc_url = "https://api.avax.network/ext/bc/C/rpc"
request_timeout_seconds = 30
max_retries = 3
retry_delay_ms = 2000
enable_caching = true
cache_ttl_seconds = 60
risk_check_interval_seconds = 60
block_confirmation_count = 12

[risk]
max_position_size_usd = 10000000.0
liquidation_threshold = 0.85
impermanent_loss_threshold = 0.03
mev_risk_threshold = 0.015
enable_real_time_monitoring = true
risk_calculation_interval_seconds = 30
enable_predictive_analytics = true
confidence_threshold = 0.85

[risk.protocol_risk_weights]
uniswap_v3 = 1.0
uniswap_v2 = 1.2
sushiswap = 1.5
curve = 1.1
balancer = 1.3
aave = 0.8
compound = 0.9
pancakeswap = 1.4
trader_joe = 1.6

[alerts]
# Configure with actual production webhook URLs
slack_webhook_url = ""
discord_webhook_url = ""
telegram_bot_token = ""
telegram_chat_id = ""
webhook_endpoints = []
enable_push_notifications = true
alert_cooldown_minutes = 15
severity_thresholds = { low = 0.05, medium = 0.2, high = 0.5, critical = 0.8 }

# Email configuration for production alerts
# [alerts.email]
# smtp_host = "smtp.gmail.com"
# smtp_port = 587
# username = "alerts@yourcompany.com"
# password = "your-app-password"
# from_address = "DeFi Risk Monitor <alerts@yourcompany.com>"
# use_tls = true

[logging]
level = "info"
format = "json"
output = "both"
file_path = "/var/log/defi-risk-monitor/app.log"
max_file_size_mb = 100
max_files = 10
enable_structured_logging = true
enable_request_logging = true
sensitive_fields = ["password", "jwt_secret", "api_key", "private_key", "webhook_url"]

[security]
# IMPORTANT: Change this in production!
jwt_secret = "CHANGE_THIS_IN_PRODUCTION_MINIMUM_32_CHARACTERS_REQUIRED"
jwt_expiration_hours = 24
enable_rate_limiting = true
max_login_attempts = 5
lockout_duration_minutes = 15
enable_2fa = true
password_min_length = 12
session_timeout_minutes = 480
enable_audit_logging = true
trusted_proxies = []  # Configure with actual proxy IPs

[monitoring]
enable_prometheus = true
prometheus_port = 9090
enable_jaeger = true
jaeger_endpoint = "http://jaeger:14268/api/traces"
enable_health_checks = true
health_check_interval_seconds = 30
metrics_retention_days = 90
enable_alerting = true
alert_manager_url = "http://alertmanager:9093"

[performance]
worker_threads = 8
max_blocking_threads = 32
enable_connection_pooling = true
cache_size_mb = 512
enable_query_caching = true
query_cache_ttl_seconds = 300
enable_compression = true
batch_size = 5000
enable_parallel_processing = true

[features]
enable_websockets = true
enable_real_time_updates = true
enable_advanced_analytics = true
enable_mev_protection = true
enable_cross_chain_monitoring = true
enable_ai_predictions = true
enable_automated_rebalancing = false  # Disabled by default for safety
enable_portfolio_optimization = true
enable_experimental_features = false
