# Development Environment Configuration
# This file contains development-specific settings

[database]
url = "postgresql://postgres:password@localhost:5434/defi_risk_monitor"
max_connections = 10
min_connections = 2
connection_timeout_seconds = 30
idle_timeout_seconds = 600
max_lifetime_seconds = 3600
enable_logging = true
slow_query_threshold_ms = 500
replica_urls = []
enable_read_replicas = false

[api]
host = "127.0.0.1"
port = 8080
cors_origins = ["http://localhost:3000", "http://localhost:3001", "http://localhost:3002"]
request_timeout_seconds = 30
max_request_size_mb = 16
rate_limit_requests_per_minute = 10000
enable_compression = true
enable_metrics = true

[blockchain]
ethereum_rpc_url = "https://eth.llamarpc.com"
ethereum_ws_url = "wss://eth.llamarpc.com"
polygon_rpc_url = "https://polygon.llamarpc.com"
arbitrum_rpc_url = "https://arbitrum.llamarpc.com"
optimism_rpc_url = "https://optimism.llamarpc.com"
bsc_rpc_url = "https://bsc.llamarpc.com"
avalanche_rpc_url = "https://avalanche.llamarpc.com"
request_timeout_seconds = 30
max_retries = 3
retry_delay_ms = 1000
enable_caching = true
cache_ttl_seconds = 300
risk_check_interval_seconds = 300
block_confirmation_count = 3

[risk]
max_position_size_usd = 1000000.0
liquidation_threshold = 0.85
impermanent_loss_threshold = 0.05
mev_risk_threshold = 0.02
enable_real_time_monitoring = false
risk_calculation_interval_seconds = 60
enable_predictive_analytics = true
confidence_threshold = 0.8

[risk.protocol_risk_weights]
uniswap_v3 = 1.0
uniswap_v2 = 1.2
sushiswap = 1.5
curve = 1.1
balancer = 1.3
aave = 0.8
compound = 0.9

[alerts]
slack_webhook_url = ""
discord_webhook_url = ""
telegram_bot_token = ""
telegram_chat_id = ""
webhook_endpoints = []
enable_push_notifications = false
alert_cooldown_minutes = 5
severity_thresholds = { low = 0.1, medium = 0.3, high = 0.7, critical = 0.9 }

[logging]
level = "debug"
format = "pretty"
output = "stdout"
file_path = ""
max_file_size_mb = 100
max_files = 5
enable_structured_logging = false
enable_request_logging = true
sensitive_fields = ["password", "jwt_secret", "api_key", "private_key"]

[security]
jwt_secret = "development-jwt-secret-change-in-production-32-chars-minimum"
jwt_expiration_hours = 168
enable_rate_limiting = false
max_login_attempts = 10
lockout_duration_minutes = 5
enable_2fa = false
password_min_length = 8
session_timeout_minutes = 480
enable_audit_logging = false
trusted_proxies = ["127.0.0.1", "::1"]

[monitoring]
enable_prometheus = true
prometheus_port = 9090
enable_jaeger = false
jaeger_endpoint = ""
enable_health_checks = true
health_check_interval_seconds = 30
metrics_retention_days = 7
enable_alerting = false
alert_manager_url = ""

[performance]
worker_threads = 4
max_blocking_threads = 16
enable_connection_pooling = true
cache_size_mb = 128
enable_query_caching = true
query_cache_ttl_seconds = 300
enable_compression = true
batch_size = 1000
enable_parallel_processing = true

[features]
enable_websockets = true
enable_real_time_updates = true
enable_advanced_analytics = true
enable_mev_protection = true
enable_cross_chain_monitoring = true
enable_ai_predictions = false
enable_automated_rebalancing = false
enable_portfolio_optimization = true
enable_experimental_features = true
