version: '3.8'

services:
  ai-service:
    build: .
    ports:
      - "8001:8001"
    environment:
      - AI_SERVICE_PORT=8001
      - PYTHONUNBUFFERED=1
    volumes:
      - ./models:/app/models  # For model persistence
      - ./logs:/app/logs      # For logging
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8001/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
