[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.19"

[rpc_endpoints]
mainnet = "https://eth-mainnet.alchemyapi.io/v2/your-api-key"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/your-api-key"
